### PR TITLE
Made IMDSSample.cs properly async

### PR DESCRIPTION
**Pull request by abatishchev**

### CODE REVIEW

**Comment by LittleBoxOfSunshine** [comment]
Hi @abatishchev, can you clarify what the improvement here is? To my eye because everything is await'd and we don't have a UI or other parent task that we're blocking the resulting execution here would be the same, just with the additional complexity of wrapping everything in tasks.

I didn't know they added async main as a language feature that's interesting, maybe I'm missing something else here as well.

**Comment by abatishchev** [comment]
hi @LittleBoxOfSunshine,

Using `Task.Result` is considered a malpractice and I don't think should be something a code sample by Microsoft should promote, see https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#async-all-the-way

Yes, adding `Task<T>` might complicate the code a little but this is modern C# that does some async I/O so it's normal and expected things to do.

`async Main` is a relatively-new feature of C#, was released with version 7.0 in late 2017, see https://devblogs.microsoft.com/dotnet/welcome-to-c-7-1/#async-main

**Comment by LittleBoxOfSunshine** [comment]
Makes sense to me. Our team is primarily made up of C++ devs, so that's good context for us to have. I'll pass it along. Thanks for making the change for us!

**Comment by abatishchev** [comment]
It was my pleasure. Thank you for a quick review and overall turnaround!

**Pull request merged**
